Complete requirements of weather app
julian3493/weather-app pull request #1
Opened 2021-03-18 19:49 UTC by julian3493

### Complete the weather app with the next requirements:
 
- Use API to get weather data
- Use async / await to process de data of the API
- Use Webpack
- Use ES6 modules
- Add images that change depending on the weather

2021-03-18 20:33 UTC, Forison requested changes
## Status::Change required❌

## Hi @julian3493 

#### Good job on this one, your Pull Request and Readme are informing, your code is organized well into modules, good job also on making sure you stuck to the ES6 syntax as required. Here some other improvement we can do to make it even better😊.

* [ ] It has error handling for `promises` or `async/await` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- Let us use error handling block when making API calls. try and catch is my favorite

* [ ] Let us always capitalize our "I" and API the latter is an abbreviation and the former is represent a you.

**[OPTIONAL]**

 * [ ] It fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location

* [ ] it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API (screenshot from Odin)

* [ ] Make sure to always capitalize your commit messages

* [ ] Adding a description to your repository is a plus, since it enhance the professionality of the repository.
* [ ]  Packages like `axios` save you the trouble of always converting your response to `json`

#### That is it, let us make these few changes and submit a re-review🙂

#### Happy coding👨‍💻

Addo Forison

2021-03-18 20:33 UTC, Forison commented on src/modules/apiData.js
> +  values.city = data.name;
**[OPTIONAL]**
* [ ] Use object destructuring to avoid repetition. we can destructure `name, weather` etc, from data.

2021-03-18 20:36 UTC, Forison commented on README.md
> +> In this project I build a small page where you can check the weather of a city it also shows temperature, humidity and sensation of temperature, i get those values using an api and another diferent
API and I should Uppercase

2021-03-18 20:38 UTC, Forison commented on src/modules/apiData.js
> +  const unit = getUnits();
* [ ] Make API calls within error handling block

2021-03-18 21:17 UTC, wathigo approved these changes
### APPROVED :heavy_check_mark: 
Great job implementing the requested changes.

**You may move on.**

**Happy Coding :computer: 
Simon Wathigo**

2021-03-19 03:21 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-03-19 05:04 UTC, merged